//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labb1_ClientOvning.PersonServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PersonServiceReference.IPerson")]
    public interface IPerson {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/EditFirstName", ReplyAction="http://tempuri.org/IPerson/EditFirstNameResponse")]
        bool EditFirstName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/EditFirstName", ReplyAction="http://tempuri.org/IPerson/EditFirstNameResponse")]
        System.Threading.Tasks.Task<bool> EditFirstNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/EditLastName", ReplyAction="http://tempuri.org/IPerson/EditLastNameResponse")]
        bool EditLastName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/EditLastName", ReplyAction="http://tempuri.org/IPerson/EditLastNameResponse")]
        System.Threading.Tasks.Task<bool> EditLastNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/EditAdress", ReplyAction="http://tempuri.org/IPerson/EditAdressResponse")]
        bool EditAdress(string adress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/EditAdress", ReplyAction="http://tempuri.org/IPerson/EditAdressResponse")]
        System.Threading.Tasks.Task<bool> EditAdressAsync(string adress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/EditTel", ReplyAction="http://tempuri.org/IPerson/EditTelResponse")]
        bool EditTel(int tel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/EditTel", ReplyAction="http://tempuri.org/IPerson/EditTelResponse")]
        System.Threading.Tasks.Task<bool> EditTelAsync(int tel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/PrintFullName", ReplyAction="http://tempuri.org/IPerson/PrintFullNameResponse")]
        string PrintFullName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/PrintFullName", ReplyAction="http://tempuri.org/IPerson/PrintFullNameResponse")]
        System.Threading.Tasks.Task<string> PrintFullNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/PrintAdress", ReplyAction="http://tempuri.org/IPerson/PrintAdressResponse")]
        string PrintAdress();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/PrintAdress", ReplyAction="http://tempuri.org/IPerson/PrintAdressResponse")]
        System.Threading.Tasks.Task<string> PrintAdressAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonChannel : Labb1_ClientOvning.PersonServiceReference.IPerson, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonClient : System.ServiceModel.ClientBase<Labb1_ClientOvning.PersonServiceReference.IPerson>, Labb1_ClientOvning.PersonServiceReference.IPerson {
        
        public PersonClient() {
        }
        
        public PersonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool EditFirstName(string name) {
            return base.Channel.EditFirstName(name);
        }
        
        public System.Threading.Tasks.Task<bool> EditFirstNameAsync(string name) {
            return base.Channel.EditFirstNameAsync(name);
        }
        
        public bool EditLastName(string name) {
            return base.Channel.EditLastName(name);
        }
        
        public System.Threading.Tasks.Task<bool> EditLastNameAsync(string name) {
            return base.Channel.EditLastNameAsync(name);
        }
        
        public bool EditAdress(string adress) {
            return base.Channel.EditAdress(adress);
        }
        
        public System.Threading.Tasks.Task<bool> EditAdressAsync(string adress) {
            return base.Channel.EditAdressAsync(adress);
        }
        
        public bool EditTel(int tel) {
            return base.Channel.EditTel(tel);
        }
        
        public System.Threading.Tasks.Task<bool> EditTelAsync(int tel) {
            return base.Channel.EditTelAsync(tel);
        }
        
        public string PrintFullName() {
            return base.Channel.PrintFullName();
        }
        
        public System.Threading.Tasks.Task<string> PrintFullNameAsync() {
            return base.Channel.PrintFullNameAsync();
        }
        
        public string PrintAdress() {
            return base.Channel.PrintAdress();
        }
        
        public System.Threading.Tasks.Task<string> PrintAdressAsync() {
            return base.Channel.PrintAdressAsync();
        }
    }
}
